version: '2'

services:
  elasticsearch:
    image: andrewvy/kuromoji-elasticsearch6:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
